### ISSUE TITLE
2nd API

### ISSUE THREAD

**Issue by ljcrapo** [NickRodriquez/Map-Method#2]
What will your 2nd Server-Side API be?

**Comment by NathanHogan16** [comment]
We haven't decided on what APIs we will be using.

**Comment by dotdlew** [comment]
we're gonna try to use Map Tiles API 
https://rapidapi.com/MapTilesApi/api/maptiles?endpoint=apiendpoint_c0dab7c5-aa3e-463c-991c-508a589e058d

suggestions are welcome, i have found several interesting map APIs
